export const QUESTIONS = [
  { id: 1, text: "Pizza ou Burger ?", a: "Pizza", b: "Burger" },
  { id: 2, text: "Mer ou Montagne ?", a: "Mer", b: "Montagne" },
  { id: 3, text: "Chien ou Chat ?", a: "Chien", b: "Chat" },
  { id: 4, text: "Matin ou Soir ?", a: "Matin", b: "Soir" },
  { id: 5, text: "Thé ou Café ?", a: "Thé", b: "Café" },
  { id: 6, text: "Sucré ou Salé ?", a: "Sucré", b: "Salé" },
  { id: 7, text: "Film ou Série ?", a: "Film", b: "Série" },
  { id: 8, text: "Resto ou Pique-nique ?", a: "Resto", b: "Pique-nique" },
  { id: 9, text: "Ville ou Campagne ?", a: "Ville", b: "Campagne" },
  { id: 10, text: "Été ou Hiver ?", a: "Été", b: "Hiver" },
  { id: 11, text: "Bain ou Douche ?", a: "Bain", b: "Douche" },
  { id: 12, text: "Livre papier ou Ebook ?", a: "Papier", b: "Ebook" },
  { id: 13, text: "Vin ou Bière ?", a: "Vin", b: "Bière" },
  { id: 14, text: "Fromage ou Dessert ?", a: "Fromage", b: "Dessert" },
  { id: 15, text: "Camping ou Hôtel ?", a: "Camping", b: "Hôtel" },
  { id: 16, text: "Van ou Train ?", a: "Van", b: "Train" },
  { id: 17, text: "Randonnée ou Bronzette ?", a: "Rando", b: "Bronzette" },
  { id: 18, text: "Cuisiner ou Commander ?", a: "Cuisiner", b: "Commander" },
  { id: 19, text: "Jeu de société ou Jeu vidéo ?", a: "Société", b: "Vidéo" },
  { id: 20, text: "Musée ou Parc d'attraction ?", a: "Musée", b: "Parc" },
  { id: 21, text: "Plante verte ou Fleurs ?", a: "Plante", b: "Fleurs" },
  { id: 22, text: "Lever de soleil ou Coucher de soleil ?", a: "Lever", b: "Coucher" },
  { id: 23, text: "Chocolat noir ou au lait ?", a: "Noir", b: "Lait" },
  { id: 24, text: "Baskets ou Chaussures de rando ?", a: "Baskets", b: "Rando" },
  { id: 25, text: "Cabane dans les bois ou Villa piscine ?", a: "Cabane", b: "Villa" },
  { id: 26, text: "Feu de cheminée ou Clim ?", a: "Cheminée", b: "Clim" },
  { id: 27, text: "Chien de berger ou Golden Retriever ?", a: "Berger", b: "Golden" },
  { id: 28, text: "Potager ou Verger ?", a: "Potager", b: "Verger" },
  { id: 29, text: "Vélo ou Marche ?", a: "Vélo", b: "Marche" },
  { id: 30, text: "Pain au choc ou Croissant ?", a: "Pain au choc", b: "Croissant" },
  { id: 31, text: "Bricolage ou Jardinage ?", a: "Bricolage", b: "Jardinage" },
  { id: 32, text: "Spontané ou Organisé ?", a: "Spontané", b: "Organisé" },
  { id: 33, text: "Cadeau surprise ou Liste de souhaits ?", a: "Surprise", b: "Liste" },
  { id: 34, text: "Massage ou Spa ?", a: "Massage", b: "Spa" },
  { id: 35, text: "Canoë ou Paddle ?", a: "Canoë", b: "Paddle" },
  { id: 36, text: "Hamac ou Transat ?", a: "Hamac", b: "Transat" },
  { id: 37, text: "Aventure ou Farniente ?", a: "Aventure", b: "Farniente" },
  { id: 38, text: "Pâtes ou Riz ?", a: "Pâtes", b: "Riz" },
  { id: 39, text: "Saut en parachute ou Plongée ?", a: "Parachute", b: "Plongée" },
  { id: 40, text: "Soirée amis ou Soirée amoureux ?", a: "Amis", b: "Amoureux" },
  { id: 41, text: "Action ou Vérité ?", a: "Action", b: "Vérité" },
  { id: 42, text: "Crêpe ou Gaufre ?", a: "Crêpe", b: "Gaufre" },
  { id: 43, text: "Chanter ou Danser ?", a: "Chanter", b: "Danser" },
  { id: 44, text: "Bruit de la pluie ou Bruit des vagues ?", a: "Pluie", b: "Vagues" },
  { id: 45, text: "Lève-tôt ou Couche-tard ?", a: "Lève-tôt", b: "Couche-tard" },
  { id: 46, text: "Minimaliste ou Collectionneur ?", a: "Minimaliste", b: "Collectionneur" },
  { id: 47, text: "Bois ou Pierre ?", a: "Bois", b: "Pierre" },
  { id: 48, text: "Froid sec ou Chaud humide ?", a: "Froid", b: "Chaud" },
  { id: 49, text: "Sac à dos ou Valise ?", a: "Sac à dos", b: "Valise" },
  { id: 50, text: "Carte papier ou GPS ?", a: "Carte", b: "GPS" }
];
