export const QUESTIONS = [
  // --- CLASSIQUES & BASIQUES ---
  { id: 1, text: "Pizza ou Burger ?", a: "Pizza", b: "Burger" },
  { id: 2, text: "Mer ou Montagne ?", a: "Mer", b: "Montagne" },
  { id: 3, text: "Chien ou Chat ?", a: "Chien", b: "Chat" },
  { id: 4, text: "Matin ou Soir ?", a: "Matin", b: "Soir" },
  { id: 5, text: "Thé ou Café ?", a: "Thé", b: "Café" },
  { id: 6, text: "Sucré ou Salé ?", a: "Sucré", b: "Salé" },
  { id: 7, text: "Film ou Série ?", a: "Film", b: "Série" },
  { id: 8, text: "Resto ou Pique-nique ?", a: "Resto", b: "Pique-nique" },
  { id: 9, text: "Ville ou Campagne ?", a: "Ville", b: "Campagne" },
  { id: 10, text: "Été ou Hiver ?", a: "Été", b: "Hiver" },
  { id: 11, text: "Bain ou Douche ?", a: "Bain", b: "Douche" },
  { id: 12, text: "Livre papier ou Ebook ?", a: "Papier", b: "Ebook" },
  { id: 13, text: "Vin ou Bière ?", a: "Vin", b: "Bière" },
  { id: 14, text: "Fromage ou Dessert ?", a: "Fromage", b: "Dessert" },
  { id: 15, text: "Camping ou Hôtel ?", a: "Camping", b: "Hôtel" },
  { id: 16, text: "Van ou Train ?", a: "Van", b: "Train" },
  { id: 17, text: "Randonnée ou Bronzette ?", a: "Rando", b: "Bronzette" },
  { id: 18, text: "Cuisiner ou Commander ?", a: "Cuisiner", b: "Commander" },
  { id: 19, text: "Jeu de société ou Jeu vidéo ?", a: "Société", b: "Vidéo" },
  { id: 20, text: "Musée ou Parc d'attraction ?", a: "Musée", b: "Parc" },
  
  // --- VIE QUOTIDIENNE ---
  { id: 21, text: "Vaisselle main ou Lave-vaisselle ?", a: "Main", b: "Machine" },
  { id: 22, text: "Ménage le samedi ou un peu tous les jours ?", a: "Samedi", b: "Tous les jours" },
  { id: 23, text: "Liste de courses ou Improvisation ?", a: "Liste", b: "Impro" },
  { id: 24, text: "Douche le matin ou le soir ?", a: "Matin", b: "Soir" },
  { id: 25, text: "Dormir volets fermés ou ouverts ?", a: "Fermés", b: "Ouverts" },
  { id: 26, text: "Chauffage à fond ou Gros pull ?", a: "Chauffage", b: "Pull" },
  { id: 27, text: "Téléphone en silencieux ou Sonnerie ?", a: "Silencieux", b: "Sonnerie" },
  { id: 28, text: "Réveil doux ou Alarme pompier ?", a: "Doux", b: "Fort" },
  { id: 29, text: "Petit-dej salé ou sucré ?", a: "Salé", b: "Sucré" },
  { id: 30, text: "S'habiller chic ou Confort ?", a: "Chic", b: "Confort" },
  
  // --- VOYAGE & AVENTURE ---
  { id: 31, text: "Valise ou Sac à dos ?", a: "Valise", b: "Sac à dos" },
  { id: 32, text: "Programme millimétré ou Aventure ?", a: "Programme", b: "Aventure" },
  { id: 33, text: "Airbnb ou Camping sauvage ?", a: "Airbnb", b: "Sauvage" },
  { id: 34, text: "Pays chauds ou Pays froids ?", a: "Chauds", b: "Froids" },
  { id: 35, text: "Avion ou Road trip ?", a: "Avion", b: "Road trip" },
  { id: 36, text: "Touristique ou Hors des sentiers ?", a: "Touriste", b: "Perdu" },
  { id: 37, text: "Photos souvenirs ou Vivre l'instant ?", a: "Photos", b: "Instant" },
  { id: 38, text: "Musée d'art ou Rando forêt ?", a: "Musée", b: "Forêt" },
  { id: 39, text: "Guide du Routard ou Google Maps ?", a: "Guide", b: "Maps" },
  { id: 40, text: "All inclusive ou Débrouille ?", a: "Inclusive", b: "Débrouille" },

  // --- NOURRITURE ---
  { id: 41, text: "Chocolat noir ou au Lait ?", a: "Noir", b: "Lait" },
  { id: 42, text: "Pâtes carbo ou Pâtes bolo ?", a: "Carbo", b: "Bolo" },
  { id: 43, text: "Vin rouge ou Vin blanc ?", a: "Rouge", b: "Blanc" },
  { id: 44, text: "Crêpe ou Gaufre ?", a: "Crêpe", b: "Gaufre" },
  { id: 45, text: "Cuisine italienne ou Asiatique ?", a: "Italienne", b: "Asiatique" },
  { id: 46, text: "Raclette ou Fondue ?", a: "Raclette", b: "Fondue" },
  { id: 47, text: "Eau plate ou gazeuse ?", a: "Plate", b: "Gazeuse" },
  { id: 48, text: "Ketchup ou Mayonnaise ?", a: "Ketchup", b: "Mayo" },
  { id: 49, text: "Pain très cuit ou Pas trop ?", a: "Cuit", b: "Blanc" },
  { id: 50, text: "Glace Vanille ou Chocolat ?", a: "Vanille", b: "Chocolat" },
  { id: 51, text: "Burger King ou McDo ?", a: "BK", b: "McDo" },
  { id: 52, text: "Sushi ou Pizza ?", a: "Sushi", b: "Pizza" },
  { id: 53, text: "Piquant ou Doux ?", a: "Piquant", b: "Doux" },
  { id: 54, text: "Viande saignante ou À point ?", a: "Saignante", b: "À point" },
  { id: 55, text: "Coca ou Ice Tea ?", a: "Coca", b: "Ice Tea" },
  { id: 56, text: "Nutella ou Confiture ?", a: "Nutella", b: "Confiture" },
  { id: 57, text: "Chips ou Saucisson ?", a: "Chips", b: "Saucisson" },
  { id: 58, text: "Tacos ou Kebab ?", a: "Tacos", b: "Kebab" },
  { id: 59, text: "Légumes ou Féculents ?", a: "Légumes", b: "Féculents" },
  { id: 60, text: "Manger tôt ou Manger tard ?", a: "Tôt", b: "Tard" },

  // --- PERSONNALITÉ ---
  { id: 61, text: "Introverti ou Extraverti ?", a: "Introverti", b: "Extraverti" },
  { id: 62, text: "Optimiste ou Réaliste ?", a: "Optimiste", b: "Réaliste" },
  { id: 63, text: "Cœur ou Raison ?", a: "Cœur", b: "Raison" },
  { id: 64, text: "Parler ou Écouter ?", a: "Parler", b: "Écouter" },
  { id: 65, text: "Pardonner ou Rencunier ?", a: "Pardonner", b: "Rencunier" },
  { id: 66, text: "Calme ou Énervé ?", a: "Calme", b: "Énervé" },
  { id: 67, text: "Cadeau utile ou Cadeau plaisir ?", a: "Utile", b: "Plaisir" },
  { id: 68, text: "Dépensier ou Économe ?", a: "Dépensier", b: "Économe" },
  { id: 69, text: "Ponctuel ou En retard ?", a: "Ponctuel", b: "Retard" },
  { id: 70, text: "Leader ou Suiveur ?", a: "Leader", b: "Suiveur" },

  // --- LOISIRS & CULTURE ---
  { id: 71, text: "Harry Potter ou Seigneur des Anneaux ?", a: "HP", b: "LOTR" },
  { id: 72, text: "Star Wars ou Marvel ?", a: "Star Wars", b: "Marvel" },
  { id: 73, text: "Rap ou Rock ?", a: "Rap", b: "Rock" },
  { id: 74, text: "Cinéma ou Netflix ?", a: "Cinéma", b: "Netflix" },
  { id: 75, text: "Roman ou BD ?", a: "Roman", b: "BD" },
  { id: 76, text: "Danse ou Sport ?", a: "Danse", b: "Sport" },
  { id: 77, text: "Peinture ou Musique ?", a: "Peinture", b: "Musique" },
  { id: 78, text: "Android ou iPhone ?", a: "Android", b: "iPhone" },
  { id: 79, text: "Twitter ou Instagram ?", a: "Twitter", b: "Insta" },
  { id: 80, text: "Youtube ou TikTok ?", a: "Youtube", b: "TikTok" },

  // --- TU PRÉFÈRES (ABSURDE & FUN) ---
  { id: 81, text: "Voler ou Être invisible ?", a: "Voler", b: "Invisible" },
  { id: 82, text: "Lire dans les pensées ou Voir le futur ?", a: "Pensées", b: "Futur" },
  { id: 83, text: "Pas d'internet ou Pas d'eau chaude ?", a: "Internet", b: "Eau chaude" },
  { id: 84, text: "Toujours dire la vérité ou Toujours mentir ?", a: "Vérité", b: "Mentir" },
  { id: 85, text: "Avoir trop chaud ou Avoir trop froid ?", a: "Chaud", b: "Froid" },
  { id: 86, text: "Vivre sous l'eau ou Dans l'espace ?", a: "Eau", b: "Espace" },
  { id: 87, text: "Être un chat ou Être un aigle ?", a: "Chat", b: "Aigle" },
  { id: 88, text: "Manger que du sucré ou que du salé ?", a: "Sucré", b: "Salé" },
  { id: 89, text: "Voyager dans le passé ou le futur ?", a: "Passé", b: "Futur" },
  { id: 90, text: "Avoir des bras de 3m ou des jambes de 3m ?", a: "Bras", b: "Jambes" },

  // --- COUPLE & AVENIR ---
  { id: 91, text: "Grand mariage ou Comité restreint ?", a: "Grand", b: "Petit" },
  { id: 92, text: "Maison campagne ou Appart ville ?", a: "Maison", b: "Appart" },
  { id: 93, text: "Chien ou Enfants ?", a: "Chien", b: "Enfants" },
  { id: 94, text: "St Valentin romantique ou Anti-St Valentin ?", a: "Romantique", b: "Osef" },
  { id: 95, text: "Dormir collés ou Chacun son espace ?", a: "Collés", b: "Espace" },
  { id: 96, text: "Bisou le matin ou Bisou le soir ?", a: "Matin", b: "Soir" },
  { id: 97, text: "Message toute la journée ou Appel le soir ?", a: "Message", b: "Appel" },
  { id: 98, text: "Jalousie ou Confiance aveugle ?", a: "Jaloux", b: "Confiance" },
  { id: 99, text: "Week-end surprise ou Week-end prévu ?", a: "Surprise", b: "Prévu" },
  { id: 100, text: "Partager le dessert ou Pas toucher ?", a: "Partager", b: "Pas toucher" },

  // --- NOUVELLES QUESTIONS MANUELLES (QUALITÉ GARANTIE) ---
  { id: 101, text: "Conducteur ou Passager ?", a: "Conducteur", b: "Passager" },
  { id: 102, text: "Argent : Écureuil ou Panier percé ?", a: "Écureuil", b: "Panier percé" },
  { id: 103, text: "Bricolage : Expert ou Catastrophe ?", a: "Expert", b: "Catastrophe" },
  { id: 104, text: "Voiture : Sportive ou Familiale ?", a: "Sportive", b: "Familiale" },
  { id: 105, text: "Vacances : Plage ou Visites culturelles ?", a: "Plage", b: "Visites" },
  { id: 106, text: "Météo : Canicule ou Grand froid ?", a: "Canicule", b: "Froid" },
  { id: 107, text: "Cadeau : Fait main ou Acheté ?", a: "Fait main", b: "Acheté" },
  { id: 108, text: "Soirée : Bar ou Maison ?", a: "Bar", b: "Maison" },
  { id: 109, text: "Musique : Écouteurs ou Enceinte ?", a: "Écouteurs", b: "Enceinte" },
  { id: 110, text: "Photo : Selfie ou Paysage ?", a: "Selfie", b: "Paysage" },
  { id: 111, text: "Vêtements : Marque ou Vintage ?", a: "Marque", b: "Vintage" },
  { id: 112, text: "Sport : Collectif ou Individuel ?", a: "Collectif", b: "Individuel" },
  { id: 113, text: "Télé : Documentaire ou Téléréalité ?", a: "Docu", b: "Téléréalité" },
  { id: 114, text: "Réseaux : Facebook ou TikTok ?", a: "Facebook", b: "TikTok" },
  { id: 115, text: "Appel : Facetime ou Audio ?", a: "Visio", b: "Audio" },
  { id: 116, text: "Message : Texte ou Vocal ?", a: "Texte", b: "Vocal" },
  { id: 117, text: "Travail : Passion ou Alimentaire ?", a: "Passion", b: "Alimentaire" },
  { id: 118, text: "Horaires : Fixes ou Flexibles ?", a: "Fixes", b: "Flexibles" },
  { id: 119, text: "Télétravail ou Bureau ?", a: "Maison", b: "Bureau" },
  { id: 120, text: "Chef ou Employé ?", a: "Chef", b: "Employé" },
  
  { id: 121, text: "Logement : Neuf ou Ancien ?", a: "Neuf", b: "Ancien" },
  { id: 122, text: "Déco : Minimaliste ou Chargée ?", a: "Minimaliste", b: "Chargée" },
  { id: 123, text: "Couleur mur : Blanc ou Coloré ?", a: "Blanc", b: "Coloré" },
  { id: 124, text: "Sol : Parquet ou Carrelage ?", a: "Parquet", b: "Carrelage" },
  { id: 125, text: "Lumière : Tamisée ou Vive ?", a: "Tamisée", b: "Vive" },
  { id: 126, text: "Plantes : Vraies ou Fausses ?", a: "Vraies", b: "Fausses" },
  { id: 127, text: "Meubles : Ikea ou Designer ?", a: "Ikea", b: "Designer" },
  { id: 128, text: "Lit : Une couette ou Deux couettes ?", a: "Une", b: "Deux" },
  { id: 129, text: "Cuisine : Ouverte ou Fermée ?", a: "Ouverte", b: "Fermée" },
  { id: 130, text: "SDB : Baignoire ou Douche italienne ?", a: "Baignoire", b: "Italienne" },

  { id: 131, text: "Super-pouvoir : Voler ou Téléportation ?", a: "Voler", b: "TP" },
  { id: 132, text: "Zombie Apocalypse : Leader ou Premier mort ?", a: "Leader", b: "Mort" },
  { id: 133, text: "Ile déserte : Couteau ou Briquet ?", a: "Couteau", b: "Briquet" },
  { id: 134, text: "Loto : Tout flamber ou Investir ?", a: "Flamber", b: "Investir" },
  { id: 135, text: "Réincarnation : Aigle ou Dauphin ?", a: "Aigle", b: "Dauphin" },
  { id: 136, text: "Voyage temps : 1900 ou 3000 ?", a: "1900", b: "3000" },
  { id: 137, text: "Aliens : Ils existent ou Pas ?", a: "Oui", b: "Non" },
  { id: 138, text: "Fantômes : J'y crois ou Conneries ?", a: "J'y crois", b: "Conneries" },
  { id: 139, text: "Destin ou Hasard ?", a: "Destin", b: "Hasard" },
  { id: 140, text: "Karma : Vrai ou Faux ?", a: "Vrai", b: "Faux" },

  { id: 141, text: "Enfant : Fille ou Garçon ?", a: "Fille", b: "Garçon" },
  { id: 142, text: "Prénom : Classique ou Original ?", a: "Classique", b: "Original" },
  { id: 143, text: "Éducation : Stricte ou Cool ?", a: "Stricte", b: "Cool" },
  { id: 144, text: "École : Privée ou Publique ?", a: "Privée", b: "Publique" },
  { id: 145, text: "Noël : En famille ou Voyage ?", a: "Famille", b: "Voyage" },
  { id: 146, text: "Dimanche : Repas famille ou Netflix ?", a: "Famille", b: "Netflix" },
  { id: 147, text: "Vieux jours : Maison retraite ou Chez soi ?", a: "Retraite", b: "Chez soi" },
  { id: 148, text: "Enterrement : Triste ou Fête ?", a: "Triste", b: "Fête" },
  { id: 149, text: "Secret : Je garde ou Je balance ?", a: "Garde", b: "Balance" },
  { id: 150, text: "Mensonge : Jamais ou Parfois utile ?", a: "Jamais", b: "Utile" }
];
