export const QUESTIONS = [
  // --- CLASSIQUES & BASIQUES ---
  { id: 1, text: "Pizza ou Burger ?", a: "Pizza", b: "Burger" },
  { id: 2, text: "Mer ou Montagne ?", a: "Mer", b: "Montagne" },
  { id: 3, text: "Chien ou Chat ?", a: "Chien", b: "Chat" },
  { id: 4, text: "Matin ou Soir ?", a: "Matin", b: "Soir" },
  { id: 5, text: "Thé ou Café ?", a: "Thé", b: "Café" },
  { id: 6, text: "Sucré ou Salé ?", a: "Sucré", b: "Salé" },
  { id: 7, text: "Film ou Série ?", a: "Film", b: "Série" },
  { id: 8, text: "Resto ou Pique-nique ?", a: "Resto", b: "Pique-nique" },
  { id: 9, text: "Ville ou Campagne ?", a: "Ville", b: "Campagne" },
  { id: 10, text: "Été ou Hiver ?", a: "Été", b: "Hiver" },
  { id: 11, text: "Bain ou Douche ?", a: "Bain", b: "Douche" },
  { id: 12, text: "Livre papier ou Ebook ?", a: "Papier", b: "Ebook" },
  { id: 13, text: "Vin ou Bière ?", a: "Vin", b: "Bière" },
  { id: 14, text: "Fromage ou Dessert ?", a: "Fromage", b: "Dessert" },
  { id: 15, text: "Camping ou Hôtel ?", a: "Camping", b: "Hôtel" },
  { id: 16, text: "Van ou Train ?", a: "Van", b: "Train" },
  { id: 17, text: "Randonnée ou Bronzette ?", a: "Rando", b: "Bronzette" },
  { id: 18, text: "Cuisiner ou Commander ?", a: "Cuisiner", b: "Commander" },
  { id: 19, text: "Jeu de société ou Jeu vidéo ?", a: "Société", b: "Vidéo" },
  { id: 20, text: "Musée ou Parc d'attraction ?", a: "Musée", b: "Parc" },
  
  // --- VIE QUOTIDIENNE ---
  { id: 21, text: "Vaisselle main ou Lave-vaisselle ?", a: "Main", b: "Machine" },
  { id: 22, text: "Ménage le samedi ou un peu tous les jours ?", a: "Samedi", b: "Tous les jours" },
  { id: 23, text: "Liste de courses ou Improvisation ?", a: "Liste", b: "Impro" },
  { id: 24, text: "Douche le matin ou le soir ?", a: "Matin", b: "Soir" },
  { id: 25, text: "Dormir volets fermés ou ouverts ?", a: "Fermés", b: "Ouverts" },
  { id: 26, text: "Chauffage à fond ou Gros pull ?", a: "Chauffage", b: "Pull" },
  { id: 27, text: "Téléphone en silencieux ou Sonnerie ?", a: "Silencieux", b: "Sonnerie" },
  { id: 28, text: "Réveil doux ou Alarme pompier ?", a: "Doux", b: "Fort" },
  { id: 29, text: "Petit-dej salé ou sucré ?", a: "Salé", b: "Sucré" },
  { id: 30, text: "S'habiller chic ou Confort ?", a: "Chic", b: "Confort" },
  
  // --- VOYAGE & AVENTURE ---
  { id: 31, text: "Valise ou Sac à dos ?", a: "Valise", b: "Sac à dos" },
  { id: 32, text: "Programme millimétré ou Aventure ?", a: "Programme", b: "Aventure" },
  { id: 33, text: "Airbnb ou Camping sauvage ?", a: "Airbnb", b: "Sauvage" },
  { id: 34, text: "Pays chauds ou Pays froids ?", a: "Chauds", b: "Froids" },
  { id: 35, text: "Avion ou Road trip ?", a: "Avion", b: "Road trip" },
  { id: 36, text: "Touristique ou Hors des sentiers ?", a: "Touriste", b: "Perdu" },
  { id: 37, text: "Photos souvenirs ou Vivre l'instant ?", a: "Photos", b: "Instant" },
  { id: 38, text: "Musée d'art ou Rando forêt ?", a: "Musée", b: "Forêt" },
  { id: 39, text: "Guide du Routard ou Google Maps ?", a: "Guide", b: "Maps" },
  { id: 40, text: "All inclusive ou Débrouille ?", a: "Inclusive", b: "Débrouille" },

  // --- NOURRITURE ---
  { id: 41, text: "Chocolat noir ou au Lait ?", a: "Noir", b: "Lait" },
  { id: 42, text: "Pâtes carbo ou Pâtes bolo ?", a: "Carbo", b: "Bolo" },
  { id: 43, text: "Vin rouge ou Vin blanc ?", a: "Rouge", b: "Blanc" },
  { id: 44, text: "Crêpe ou Gaufre ?", a: "Crêpe", b: "Gaufre" },
  { id: 45, text: "Cuisine italienne ou Asiatique ?", a: "Italienne", b: "Asiatique" },
  { id: 46, text: "Raclette ou Fondue ?", a: "Raclette", b: "Fondue" },
  { id: 47, text: "Eau plate ou gazeuse ?", a: "Plate", b: "Gazeuse" },
  { id: 48, text: "Ketchup ou Mayonnaise ?", a: "Ketchup", b: "Mayo" },
  { id: 49, text: "Pain très cuit ou Pas trop ?", a: "Cuit", b: "Blanc" },
  { id: 50, text: "Glace Vanille ou Chocolat ?", a: "Vanille", b: "Chocolat" },
  { id: 51, text: "Burger King ou McDo ?", a: "BK", b: "McDo" },
  { id: 52, text: "Sushi ou Pizza ?", a: "Sushi", b: "Pizza" },
  { id: 53, text: "Piquant ou Doux ?", a: "Piquant", b: "Doux" },
  { id: 54, text: "Viande saignante ou À point ?", a: "Saignante", b: "À point" },
  { id: 55, text: "Coca ou Ice Tea ?", a: "Coca", b: "Ice Tea" },
  { id: 56, text: "Nutella ou Confiture ?", a: "Nutella", b: "Confiture" },
  { id: 57, text: "Chips ou Saucisson ?", a: "Chips", b: "Saucisson" },
  { id: 58, text: "Tacos ou Kebab ?", a: "Tacos", b: "Kebab" },
  { id: 59, text: "Légumes ou Féculents ?", a: "Légumes", b: "Féculents" },
  { id: 60, text: "Manger tôt ou Manger tard ?", a: "Tôt", b: "Tard" },

  // --- PERSONNALITÉ ---
  { id: 61, text: "Introverti ou Extraverti ?", a: "Introverti", b: "Extraverti" },
  { id: 62, text: "Optimiste ou Réaliste ?", a: "Optimiste", b: "Réaliste" },
  { id: 63, text: "Cœur ou Raison ?", a: "Cœur", b: "Raison" },
  { id: 64, text: "Parler ou Écouter ?", a: "Parler", b: "Écouter" },
  { id: 65, text: "Pardonner ou Rencunier ?", a: "Pardonner", b: "Rencunier" },
  { id: 66, text: "Calme ou Énervé ?", a: "Calme", b: "Énervé" },
  { id: 67, text: "Cadeau utile ou Cadeau plaisir ?", a: "Utile", b: "Plaisir" },
  { id: 68, text: "Dépensier ou Économe ?", a: "Dépensier", b: "Économe" },
  { id: 69, text: "Ponctuel ou En retard ?", a: "Ponctuel", b: "Retard" },
  { id: 70, text: "Leader ou Suiveur ?", a: "Leader", b: "Suiveur" },

  // --- LOISIRS & CULTURE ---
  { id: 71, text: "Harry Potter ou Seigneur des Anneaux ?", a: "HP", b: "LOTR" },
  { id: 72, text: "Star Wars ou Marvel ?", a: "Star Wars", b: "Marvel" },
  { id: 73, text: "Rap ou Rock ?", a: "Rap", b: "Rock" },
  { id: 74, text: "Cinéma ou Netflix ?", a: "Cinéma", b: "Netflix" },
  { id: 75, text: "Roman ou BD ?", a: "Roman", b: "BD" },
  { id: 76, text: "Danse ou Sport ?", a: "Danse", b: "Sport" },
  { id: 77, text: "Peinture ou Musique ?", a: "Peinture", b: "Musique" },
  { id: 78, text: "Android ou iPhone ?", a: "Android", b: "iPhone" },
  { id: 79, text: "Twitter ou Instagram ?", a: "Twitter", b: "Insta" },
  { id: 80, text: "Youtube ou TikTok ?", a: "Youtube", b: "TikTok" },

  // --- TU PRÉFÈRES (ABSURDE & FUN) ---
  { id: 81, text: "Voler ou Être invisible ?", a: "Voler", b: "Invisible" },
  { id: 82, text: "Lire dans les pensées ou Voir le futur ?", a: "Pensées", b: "Futur" },
  { id: 83, text: "Pas d'internet ou Pas d'eau chaude ?", a: "Internet", b: "Eau chaude" },
  { id: 84, text: "Toujours dire la vérité ou Toujours mentir ?", a: "Vérité", b: "Mentir" },
  { id: 85, text: "Avoir trop chaud ou Avoir trop froid ?", a: "Chaud", b: "Froid" },
  { id: 86, text: "Vivre sous l'eau ou Dans l'espace ?", a: "Eau", b: "Espace" },
  { id: 87, text: "Être un chat ou Être un aigle ?", a: "Chat", b: "Aigle" },
  { id: 88, text: "Manger que du sucré ou que du salé ?", a: "Sucré", b: "Salé" },
  { id: 89, text: "Voyager dans le passé ou le futur ?", a: "Passé", b: "Futur" },
  { id: 90, text: "Avoir des bras de 3m ou des jambes de 3m ?", a: "Bras", b: "Jambes" },

  // --- COUPLE & AVENIR ---
  { id: 91, text: "Grand mariage ou Comité restreint ?", a: "Grand", b: "Petit" },
  { id: 92, text: "Maison campagne ou Appart ville ?", a: "Maison", b: "Appart" },
  { id: 93, text: "Chien ou Enfants ?", a: "Chien", b: "Enfants" },
  { id: 94, text: "St Valentin romantique ou Anti-St Valentin ?", a: "Romantique", b: "Osef" },
  { id: 95, text: "Dormir collés ou Chacun son espace ?", a: "Collés", b: "Espace" },
  { id: 96, text: "Bisou le matin ou Bisou le soir ?", a: "Matin", b: "Soir" },
  { id: 97, text: "Message toute la journée ou Appel le soir ?", a: "Message", b: "Appel" },
  { id: 98, text: "Jalousie ou Confiance aveugle ?", a: "Jaloux", b: "Confiance" },
  { id: 99, text: "Week-end surprise ou Week-end prévu ?", a: "Surprise", b: "Prévu" },
  { id: 100, text: "Partager le dessert ou Pas toucher ?", a: "Partager", b: "Pas toucher" },

  // --- BATCH 2 (HABITUDES) ---
  { id: 101, text: "Conducteur ou Passager ?", a: "Conducteur", b: "Passager" },
  { id: 102, text: "Argent : Écureuil ou Panier percé ?", a: "Écureuil", b: "Panier percé" },
  { id: 103, text: "Bricolage : Expert ou Catastrophe ?", a: "Expert", b: "Catastrophe" },
  { id: 104, text: "Voiture : Sportive ou Familiale ?", a: "Sportive", b: "Familiale" },
  { id: 105, text: "Vacances : Plage ou Visites culturelles ?", a: "Plage", b: "Visites" },
  { id: 106, text: "Météo : Canicule ou Grand froid ?", a: "Canicule", b: "Froid" },
  { id: 107, text: "Cadeau : Fait main ou Acheté ?", a: "Fait main", b: "Acheté" },
  { id: 108, text: "Soirée : Bar ou Maison ?", a: "Bar", b: "Maison" },
  { id: 109, text: "Musique : Écouteurs ou Enceinte ?", a: "Écouteurs", b: "Enceinte" },
  { id: 110, text: "Photo : Selfie ou Paysage ?", a: "Selfie", b: "Paysage" },
  { id: 111, text: "Vêtements : Marque ou Vintage ?", a: "Marque", b: "Vintage" },
  { id: 112, text: "Sport : Collectif ou Individuel ?", a: "Collectif", b: "Individuel" },
  { id: 113, text: "Télé : Documentaire ou Téléréalité ?", a: "Docu", b: "Téléréalité" },
  { id: 114, text: "Réseaux : Facebook ou TikTok ?", a: "Facebook", b: "TikTok" },
  { id: 115, text: "Appel : Facetime ou Audio ?", a: "Visio", b: "Audio" },
  { id: 116, text: "Message : Texte ou Vocal ?", a: "Texte", b: "Vocal" },
  { id: 117, text: "Travail : Passion ou Alimentaire ?", a: "Passion", b: "Alimentaire" },
  { id: 118, text: "Horaires : Fixes ou Flexibles ?", a: "Fixes", b: "Flexibles" },
  { id: 119, text: "Télétravail ou Bureau ?", a: "Maison", b: "Bureau" },
  { id: 120, text: "Chef ou Employé ?", a: "Chef", b: "Employé" },
  
  { id: 121, text: "Logement : Neuf ou Ancien ?", a: "Neuf", b: "Ancien" },
  { id: 122, text: "Déco : Minimaliste ou Chargée ?", a: "Minimaliste", b: "Chargée" },
  { id: 123, text: "Couleur mur : Blanc ou Coloré ?", a: "Blanc", b: "Coloré" },
  { id: 124, text: "Sol : Parquet ou Carrelage ?", a: "Parquet", b: "Carrelage" },
  { id: 125, text: "Lumière : Tamisée ou Vive ?", a: "Tamisée", b: "Vive" },
  { id: 126, text: "Plantes : Vraies ou Fausses ?", a: "Vraies", b: "Fausses" },
  { id: 127, text: "Meubles : Ikea ou Designer ?", a: "Ikea", b: "Designer" },
  { id: 128, text: "Lit : Une couette ou Deux couettes ?", a: "Une", b: "Deux" },
  { id: 129, text: "Cuisine : Ouverte ou Fermée ?", a: "Ouverte", b: "Fermée" },
  { id: 130, text: "SDB : Baignoire ou Douche italienne ?", a: "Baignoire", b: "Italienne" },

  { id: 131, text: "Super-pouvoir : Voler ou Téléportation ?", a: "Voler", b: "TP" },
  { id: 132, text: "Zombie Apocalypse : Leader ou Premier mort ?", a: "Leader", b: "Mort" },
  { id: 133, text: "Ile déserte : Couteau ou Briquet ?", a: "Couteau", b: "Briquet" },
  { id: 134, text: "Loto : Tout flamber ou Investir ?", a: "Flamber", b: "Investir" },
  { id: 135, text: "Réincarnation : Aigle ou Dauphin ?", a: "Aigle", b: "Dauphin" },
  { id: 136, text: "Voyage temps : 1900 ou 3000 ?", a: "1900", b: "3000" },
  { id: 137, text: "Aliens : Ils existent ou Pas ?", a: "Oui", b: "Non" },
  { id: 138, text: "Fantômes : J'y crois ou Conneries ?", a: "J'y crois", b: "Conneries" },
  { id: 139, text: "Destin ou Hasard ?", a: "Destin", b: "Hasard" },
  { id: 140, text: "Karma : Vrai ou Faux ?", a: "Vrai", b: "Faux" },

  { id: 141, text: "Enfant : Fille ou Garçon ?", a: "Fille", b: "Garçon" },
  { id: 142, text: "Prénom : Classique ou Original ?", a: "Classique", b: "Original" },
  { id: 143, text: "Éducation : Stricte ou Cool ?", a: "Stricte", b: "Cool" },
  { id: 144, text: "École : Privée ou Publique ?", a: "Privée", b: "Publique" },
  { id: 145, text: "Noël : En famille ou Voyage ?", a: "Famille", b: "Voyage" },
  { id: 146, text: "Dimanche : Repas famille ou Netflix ?", a: "Famille", b: "Netflix" },
  { id: 147, text: "Vieux jours : Maison retraite ou Chez soi ?", a: "Retraite", b: "Chez soi" },
  { id: 148, text: "Enterrement : Triste ou Fête ?", a: "Triste", b: "Fête" },
  { id: 149, text: "Secret : Je garde ou Je balance ?", a: "Garde", b: "Balance" },
  { id: 150, text: "Mensonge : Jamais ou Parfois utile ?", a: "Jamais", b: "Utile" },

  // --- BATCH 3 (NOUVEAUX) ---
  { id: 151, text: "Dentifrice : Avant ou Après petit-dej ?", a: "Avant", b: "Après" },
  { id: 152, text: "Pyjama : Soie ou T-shirt troué ?", a: "Soie", b: "T-shirt troué" },
  { id: 153, text: "Chaussettes au lit : Oui ou Non ?", a: "Oui", b: "Non" },
  { id: 154, text: "Oreiller : Un seul ou Une montagne ?", a: "Un seul", b: "Montagne" },
  { id: 155, text: "Côté du lit : Gauche ou Droite ?", a: "Gauche", b: "Droite" },
  { id: 156, text: "Moustique : Je chasse ou Je me cache ?", a: "Chasse", b: "Cache" },
  { id: 157, text: "Réveil : Je me lève ou Snooze 10 fois ?", a: "Direct", b: "Snooze" },
  { id: 158, text: "Petit-déj : Au lit ou À table ?", a: "Lit", b: "Table" },
  { id: 159, text: "Café : Noir ou Sucre/Lait ?", a: "Noir", b: "Lait/Sucre" },
  { id: 160, text: "Tartine : Beurre ou Nutella ?", a: "Beurre", b: "Nutella" },

  { id: 161, text: "Travail : Musique ou Silence absolu ?", a: "Musique", b: "Silence" },
  { id: 162, text: "Réunion : Caméra on ou off ?", a: "On", b: "Off" },
  { id: 163, text: "Bureau : Rangé ou Chaos ?", a: "Rangé", b: "Chaos" },
  { id: 164, text: "Note : Papier ou Numérique ?", a: "Papier", b: "Numérique" },
  { id: 165, text: "Mail : Inbox Zero ou 1000 non lus ?", a: "Zero", b: "1000+" },
  { id: 166, text: "Stress : Je gère ou Panique ?", a: "Gère", b: "Panique" },
  { id: 167, text: "Ambition : Carrière ou Vie perso ?", a: "Carrière", b: "Vie perso" },
  { id: 168, text: "Salaire : Fixe ou Variable ?", a: "Fixe", b: "Variable" },
  { id: 169, text: "Collègues : Amis ou Juste collègues ?", a: "Amis", b: "Collègues" },
  { id: 170, text: "Retraite : À 50 ans ou Jamais ?", a: "50 ans", b: "Jamais" },

  { id: 171, text: "Sport : Matin ou Soir ?", a: "Matin", b: "Soir" },
  { id: 172, text: "Film : VO ou VF ?", a: "VO", b: "VF" },
  { id: 173, text: "Cinéma : Popcorn ou Rien ?", a: "Popcorn", b: "Rien" },
  { id: 174, text: "Série : Binge-watching ou 1/semaine ?", a: "Binge", b: "1/semaine" },
  { id: 175, text: "Musique : Rap ou Classique ?", a: "Rap", b: "Classique" },
  { id: 176, text: "Concert : Fosse ou Gradin ?", a: "Fosse", b: "Gradin" },
  { id: 177, text: "Soirée : Danse ou Discussion ?", a: "Danse", b: "Discussion" },
  { id: 178, text: "Alcool : Modération ou Excès ?", a: "Modération", b: "Excès" },
  { id: 179, text: "Lendemain : Gueule de bois ou Frais ?", a: "PLS", b: "Frais" },
  { id: 180, text: "Sport à la télé : Foot ou Rugby ?", a: "Foot", b: "Rugby" },

  { id: 181, text: "Mensonge pieux : Acceptable ou Non ?", a: "Acceptable", b: "Non" },
  { id: 182, text: "Vengeance : Plat froid ou Pardon ?", a: "Vengeance", b: "Pardon" },
  { id: 183, text: "Destin : Tout est écrit ou Libre arbitre ?", a: "Écrit", b: "Libre" },
  { id: 184, text: "Spiritualité : Croyant ou Athée ?", a: "Croyant", b: "Athée" },
  { id: 185, text: "Politique : Engagé ou Indifférent ?", a: "Engagé", b: "Osef" },
  { id: 186, text: "Écologie : Militant ou Je fais ce que je peux ?", a: "Militant", b: "Mon mieux" },
  { id: 187, text: "Argent : Sécurité ou Liberté ?", a: "Sécurité", b: "Liberté" },
  { id: 188, text: "Amitié : Peu de vrais ou Plein de potes ?", a: "Peu", b: "Plein" },
  { id: 189, text: "Famille : Devoir ou Choix ?", a: "Devoir", b: "Choix" },
  { id: 190, text: "Nostalgie : C'était mieux avant ou Futur ?", a: "Avant", b: "Futur" },

  { id: 191, text: "Saison : Printemps ou Automne ?", a: "Printemps", b: "Automne" },
  { id: 192, text: "Glace : Pot ou Cornet ?", a: "Pot", b: "Cornet" },
  { id: 193, text: "Pizza : Base tomate ou Crème ?", a: "Tomate", b: "Crème" },
  { id: 194, text: "Fromage : Puant ou Doux ?", a: "Puant", b: "Doux" },
  { id: 195, text: "Eau : Robinet ou Bouteille ?", a: "Robinet", b: "Bouteille" },
  { id: 196, text: "Transport : Voiture ou Vélo ?", a: "Voiture", b: "Vélo" },
  { id: 197, text: "Couleur : Noir ou Blanc ?", a: "Noir", b: "Blanc" },
  { id: 198, text: "Or ou Argent ?", a: "Or", b: "Argent" },
  { id: 199, text: "Cheveux : Longs ou Courts ?", a: "Longs", b: "Courts" },
  { id: 200, text: "Barbe : Rasé ou Barbu ?", a: "Rasé", b: "Barbu" },

  { id: 201, text: "Voyage : Mer ou Océan ?", a: "Mer", b: "Océan" },
  { id: 202, text: "Montagne : Ski ou Rando d'été ?", a: "Ski", b: "Rando" },
  { id: 203, text: "Ville : Paris ou New York ?", a: "Paris", b: "NY" },
  { id: 204, text: "Asie ou Amérique ?", a: "Asie", b: "Amérique" },
  { id: 205, text: "Afrique ou Europe ?", a: "Afrique", b: "Europe" },
  { id: 206, text: "Train : Fenêtre ou Couloir ?", a: "Fenêtre", b: "Couloir" },
  { id: 207, text: "Avion : Hublot ou Couloir ?", a: "Hublot", b: "Couloir" },
  { id: 208, text: "Valise : Roulée ou Pliée ?", a: "Roulée", b: "Pliée" },
  { id: 209, text: "Photos : Paysages ou Nous ?", a: "Paysages", b: "Nous" },
  { id: 210, text: "Souvenir : Magnet ou Artisanat ?", a: "Magnet", b: "Artisanat" },

  { id: 211, text: "Dispute : On boude ou On crie ?", a: "Boude", b: "Crie" },
  { id: 212, text: "Réconciliation : Sur l'oreiller ou Discussion ?", a: "Oreiller", b: "Discussion" },
  { id: 213, text: "Jalousie : Mignon ou Toxique ?", a: "Mignon", b: "Toxique" },
  { id: 214, text: "Ex : Amis ou Inconnus ?", a: "Amis", b: "Inconnus" },
  { id: 215, text: "Belle-famille : Adorable ou Encombrante ?", a: "Adorable", b: "Lourde" },
  { id: 216, text: "Tâches : 50/50 ou Chacun sa spé ?", a: "50/50", b: "Spé" },
  { id: 217, text: "Cuisine : Ensemble ou Chacun son tour ?", a: "Ensemble", b: "Tour" },
  { id: 218, text: "Courses : Corvée ou Plaisir ?", a: "Corvée", b: "Plaisir" },
  { id: 219, text: "Budget : Compte commun ou Séparé ?", a: "Commun", b: "Séparé" },
  { id: 220, text: "Projets : Long terme ou Au jour le jour ?", a: "Long terme", b: "Carpe Diem" },

  { id: 221, text: "Oeufs : Brouillés ou Au plat ?", a: "Brouillés", b: "Plat" },
  { id: 222, text: "Cuisson : Beurre ou Huile d'olive ?", a: "Beurre", b: "Huile" },
  { id: 223, text: "Viande : Rouge ou Blanche ?", a: "Rouge", b: "Blanche" },
  { id: 224, text: "Poisson : Cuit ou Cru (Sushi) ?", a: "Cuit", b: "Cru" },
  { id: 225, text: "Dessert : Fruit ou Gâteau ?", a: "Fruit", b: "Gâteau" },
  { id: 226, text: "Goûter : Oui ou Non ?", a: "Oui", b: "Non" },
  { id: 227, text: "Grignotage : Salé ou Sucré ?", a: "Salé", b: "Sucré" },
  { id: 228, text: "Boisson : Vin ou Soda ?", a: "Vin", b: "Soda" },
  { id: 229, text: "Café : Expresso ou Allongé ?", a: "Expresso", b: "Allongé" },
  { id: 230, text: "Thé : Vert ou Noir ?", a: "Vert", b: "Noir" },

  { id: 231, text: "Loto : Tour du monde ou Maison de rêve ?", a: "Voyage", b: "Maison" },
  { id: 232, text: "Super-pouvoir : Force ou Intelligence ?", a: "Force", b: "Intelligence" },
  { id: 233, text: "Apocalypse : Arme ou Nourriture ?", a: "Arme", b: "Bouffe" },
  { id: 234, text: "Prison : Évasion ou Bonne conduite ?", a: "Évasion", b: "Sage" },
  { id: 235, text: "Temps : Arrêter le temps ou Remonter ?", a: "Pause", b: "Rewind" },
  { id: 236, text: "Animal : Chien ou Loup ?", a: "Chien", b: "Loup" },
  { id: 237, text: "Animal : Chat ou Tigre ?", a: "Chat", b: "Tigre" },
  { id: 238, text: "Nature : Forêt ou Désert ?", a: "Forêt", b: "Désert" },
  { id: 239, text: "Nature : Pluie ou Neige ?", a: "Pluie", b: "Neige" },
  { id: 240, text: "Nature : Orage ou Grand soleil ?", a: "Orage", b: "Soleil" },

  { id: 241, text: "Stylo : Bleu ou Noir ?", a: "Bleu", b: "Noir" },
  { id: 242, text: "Cahier : Rayures ou Carreaux ?", a: "Rayures", b: "Carreaux" },
  { id: 243, text: "Ordinateur : Mac ou PC ?", a: "Mac", b: "PC" },
  { id: 244, text: "Console : PlayStation ou Xbox ?", a: "PS", b: "Xbox" },
  { id: 245, text: "Voiture : Manuelle ou Auto ?", a: "Manuelle", b: "Auto" },
  { id: 246, text: "Maison : Etage ou Plain-pied ?", a: "Etage", b: "Plain-pied" },
  { id: 247, text: "Jardin : Piscine ou Potager ?", a: "Piscine", b: "Potager" },
  { id: 248, text: "Douche : Gel douche ou Savon ?", a: "Gel", b: "Savon" },
  { id: 249, text: "Cheveux : Séchage air ou Sèche-cheveux ?", a: "Air", b: "Machine" },
  { id: 250, text: "Dents : Brosse manuelle ou Électrique ?", a: "Manuelle", b: "Électrique" }
];
